[package]
name = "timers"
version = "0.1.0"
authors = ["Vivek R <123vivekr@gmail.com>"]
edition = "2018"

[dependencies]
notify-rust = "4"
figlet-rs = "0.1.3"
tokio = { version = "1.8", features = ["time", "macros", "rt-multi-thread"] }
